/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClubRouteImport } from './routes/club'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as OpinionRouteImport } from './routes/opinion'
import { Route as AdminAppRouteRouteImport } from './routes/admin/app/route'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminAppIndexRouteImport } from './routes/admin/app/index'
import { Route as AdminAppCampanasRouteImport } from './routes/admin/app/campanas'
import { Route as AdminAppClientesRouteImport } from './routes/admin/app/clientes'
import { Route as AdminAppConfiguracionRouteImport } from './routes/admin/app/configuracion'
import { Route as AdminAppOpinionesRouteImport } from './routes/admin/app/opiniones'
import { Route as AdminAppProductosRouteImport } from './routes/admin/app/productos'
import { Route as AdminAppQrRouteImport } from './routes/admin/app/qr'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClubRoute = ClubRouteImport.update({
  id: '/club',
  path: '/club',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const OpinionRoute = OpinionRouteImport.update({
  id: '/opinion',
  path: '/opinion',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAppRouteRoute = AdminAppRouteRouteImport.update({
  id: '/admin/app',
  path: '/admin/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAppIndexRoute = AdminAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAppRouteRoute,
} as any)
const AdminAppCampanasRoute = AdminAppCampanasRouteImport.update({
  id: '/campanas',
  path: '/campanas',
  getParentRoute: () => AdminAppRouteRoute,
} as any)
const AdminAppClientesRoute = AdminAppClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AdminAppRouteRoute,
} as any)
const AdminAppConfiguracionRoute = AdminAppConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => AdminAppRouteRoute,
} as any)
const AdminAppOpinionesRoute = AdminAppOpinionesRouteImport.update({
  id: '/opiniones',
  path: '/opiniones',
  getParentRoute: () => AdminAppRouteRoute,
} as any)
const AdminAppProductosRoute = AdminAppProductosRouteImport.update({
  id: '/productos',
  path: '/productos',
  getParentRoute: () => AdminAppRouteRoute,
} as any)
const AdminAppQrRoute = AdminAppQrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => AdminAppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/club': typeof ClubRoute
  '/contacto': typeof ContactoRoute
  '/menu': typeof MenuRoute
  '/opinion': typeof OpinionRoute
  '/admin/app': typeof AdminAppRouteRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/app/campanas': typeof AdminAppCampanasRoute
  '/admin/app/clientes': typeof AdminAppClientesRoute
  '/admin/app/configuracion': typeof AdminAppConfiguracionRoute
  '/admin/app/opiniones': typeof AdminAppOpinionesRoute
  '/admin/app/productos': typeof AdminAppProductosRoute
  '/admin/app/qr': typeof AdminAppQrRoute
  '/admin/app/': typeof AdminAppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/club': typeof ClubRoute
  '/contacto': typeof ContactoRoute
  '/menu': typeof MenuRoute
  '/opinion': typeof OpinionRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/app/campanas': typeof AdminAppCampanasRoute
  '/admin/app/clientes': typeof AdminAppClientesRoute
  '/admin/app/configuracion': typeof AdminAppConfiguracionRoute
  '/admin/app/opiniones': typeof AdminAppOpinionesRoute
  '/admin/app/productos': typeof AdminAppProductosRoute
  '/admin/app/qr': typeof AdminAppQrRoute
  '/admin/app': typeof AdminAppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/club': typeof ClubRoute
  '/contacto': typeof ContactoRoute
  '/menu': typeof MenuRoute
  '/opinion': typeof OpinionRoute
  '/admin/app': typeof AdminAppRouteRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/app/campanas': typeof AdminAppCampanasRoute
  '/admin/app/clientes': typeof AdminAppClientesRoute
  '/admin/app/configuracion': typeof AdminAppConfiguracionRoute
  '/admin/app/opiniones': typeof AdminAppOpinionesRoute
  '/admin/app/productos': typeof AdminAppProductosRoute
  '/admin/app/qr': typeof AdminAppQrRoute
  '/admin/app/': typeof AdminAppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/club'
    | '/contacto'
    | '/menu'
    | '/opinion'
    | '/admin/app'
    | '/admin/login'
    | '/admin/app/campanas'
    | '/admin/app/clientes'
    | '/admin/app/configuracion'
    | '/admin/app/opiniones'
    | '/admin/app/productos'
    | '/admin/app/qr'
    | '/admin/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/club'
    | '/contacto'
    | '/menu'
    | '/opinion'
    | '/admin/login'
    | '/admin/app/campanas'
    | '/admin/app/clientes'
    | '/admin/app/configuracion'
    | '/admin/app/opiniones'
    | '/admin/app/productos'
    | '/admin/app/qr'
    | '/admin/app'
  id:
    | '__root__'
    | '/'
    | '/club'
    | '/contacto'
    | '/menu'
    | '/opinion'
    | '/admin/app'
    | '/admin/login'
    | '/admin/app/campanas'
    | '/admin/app/clientes'
    | '/admin/app/configuracion'
    | '/admin/app/opiniones'
    | '/admin/app/productos'
    | '/admin/app/qr'
    | '/admin/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClubRoute: typeof ClubRoute
  ContactoRoute: typeof ContactoRoute
  MenuRoute: typeof MenuRoute
  OpinionRoute: typeof OpinionRoute
  AdminAppRouteRoute: typeof AdminAppRouteRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/club': {
      id: '/club'
      path: '/club'
      fullPath: '/club'
      preLoaderRoute: typeof ClubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opinion': {
      id: '/opinion'
      path: '/opinion'
      fullPath: '/opinion'
      preLoaderRoute: typeof OpinionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/app': {
      id: '/admin/app'
      path: '/admin/app'
      fullPath: '/admin/app'
      preLoaderRoute: typeof AdminAppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/app/': {
      id: '/admin/app/'
      path: '/'
      fullPath: '/admin/app/'
      preLoaderRoute: typeof AdminAppIndexRouteImport
      parentRoute: typeof AdminAppRouteRoute
    }
    '/admin/app/campanas': {
      id: '/admin/app/campanas'
      path: '/campanas'
      fullPath: '/admin/app/campanas'
      preLoaderRoute: typeof AdminAppCampanasRouteImport
      parentRoute: typeof AdminAppRouteRoute
    }
    '/admin/app/clientes': {
      id: '/admin/app/clientes'
      path: '/clientes'
      fullPath: '/admin/app/clientes'
      preLoaderRoute: typeof AdminAppClientesRouteImport
      parentRoute: typeof AdminAppRouteRoute
    }
    '/admin/app/configuracion': {
      id: '/admin/app/configuracion'
      path: '/configuracion'
      fullPath: '/admin/app/configuracion'
      preLoaderRoute: typeof AdminAppConfiguracionRouteImport
      parentRoute: typeof AdminAppRouteRoute
    }
    '/admin/app/opiniones': {
      id: '/admin/app/opiniones'
      path: '/opiniones'
      fullPath: '/admin/app/opiniones'
      preLoaderRoute: typeof AdminAppOpinionesRouteImport
      parentRoute: typeof AdminAppRouteRoute
    }
    '/admin/app/productos': {
      id: '/admin/app/productos'
      path: '/productos'
      fullPath: '/admin/app/productos'
      preLoaderRoute: typeof AdminAppProductosRouteImport
      parentRoute: typeof AdminAppRouteRoute
    }
    '/admin/app/qr': {
      id: '/admin/app/qr'
      path: '/qr'
      fullPath: '/admin/app/qr'
      preLoaderRoute: typeof AdminAppQrRouteImport
      parentRoute: typeof AdminAppRouteRoute
    }
  }
}

interface AdminAppRouteRouteChildren {
  AdminAppCampanasRoute: typeof AdminAppCampanasRoute
  AdminAppClientesRoute: typeof AdminAppClientesRoute
  AdminAppConfiguracionRoute: typeof AdminAppConfiguracionRoute
  AdminAppOpinionesRoute: typeof AdminAppOpinionesRoute
  AdminAppProductosRoute: typeof AdminAppProductosRoute
  AdminAppQrRoute: typeof AdminAppQrRoute
  AdminAppIndexRoute: typeof AdminAppIndexRoute
}

const AdminAppRouteRouteChildren: AdminAppRouteRouteChildren = {
  AdminAppCampanasRoute: AdminAppCampanasRoute,
  AdminAppClientesRoute: AdminAppClientesRoute,
  AdminAppConfiguracionRoute: AdminAppConfiguracionRoute,
  AdminAppOpinionesRoute: AdminAppOpinionesRoute,
  AdminAppProductosRoute: AdminAppProductosRoute,
  AdminAppQrRoute: AdminAppQrRoute,
  AdminAppIndexRoute: AdminAppIndexRoute,
}

const AdminAppRouteRouteWithChildren = AdminAppRouteRoute._addFileChildren(
  AdminAppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClubRoute: ClubRoute,
  ContactoRoute: ContactoRoute,
  MenuRoute: MenuRoute,
  OpinionRoute: OpinionRoute,
  AdminAppRouteRoute: AdminAppRouteRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
